dist: trusty
sudo: false
language: cpp

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - cppcheck

      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
    - eval "${MATRIX_EVAL}"

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - BOOST_DIR=${DEPS_DIR}/boost
  - BOOST_URL="http://github.com/boostorg/boost.git"
  - |
    travis_retry git clone --depth 1 --recursive ${BOOST_URL} ${BOOST_DIR} || exit 1
          (cd ${BOOST_DIR} && ./bootstrap.sh && ./b2 headers) || exit 1
    CMAKE_OPTIONS+=" -DBOOST_ROOT=${BOOST_DIR}"
  - cd ${TRAVIS_BUILD_DIR}

script:
  - mkdir bin
  - cd bin/
  - cmake ..
  - scan-build cmake --build . -- -j2
  - ./xtsslib_test
  - cd ..
  - cppcheck --quiet --error-exitcode=1 -f -I. -I./test -I./interprocess -I./fixed-container/include ./test/*.cpp
