image:
- Visual Studio 2017
clone_folder: C:\project\xtsslib
clone_script:
- cmd: git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
- cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%
build_script:
- cmd: >-
    mkdir build

    cd build
    
    cmake C:\project\xtsslib -G "Visual Studio 15"
    
    cmake --build .
    
    C:\project\xtsslib\build\Debug\xtsslib_test.exe


